title: "Aswin Krishna — Blog"
email: 733nwolf@gmail.com
description: "CTF writeups and pentesting blog"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://is-a.dev"
markdown: kramdown
theme: minima
permalink: /:categories/:year/:month/:day/:title/

# Collections & defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"